# Generated by Django 3.1.7 on 2021-09-26 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(max_length=30)),
                ('Amount_paid', models.IntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Student_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosellApp.student')),
            ],
        ),
    ]
