# Generated by Django 3.1.7 on 2021-09-26 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount_paid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
