# Generated by Django 3.1.4 on 2021-10-02 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CosellApp', '0005_auto_20211002_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='User_Name',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='id',
        ),
        migrations.AddField(
            model_name='faq',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faq',
            name='UserName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
