# Generated by Django 3.2.7 on 2021-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0008_auto_20211007_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Photo',
            field=models.ImageField(default='Resume_image.jpeg', upload_to='ProductImages'),
        ),
    ]
