# Generated by Django 3.2.7 on 2021-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0009_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Photo',
            field=models.ImageField(default='Balti.jpg', upload_to='ProductImages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Resume_image.jpeg', upload_to='profile_pics'),
        ),
    ]
