# Generated by Django 3.2.7 on 2021-10-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0010_auto_20211007_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CosellApp.payment'),
        ),
    ]
