# Generated by Django 3.1.7 on 2021-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0011_alter_product_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.PositiveIntegerField(),
        ),
    ]
