# Generated by Django 3.1.6 on 2021-10-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosellApp', '0012_auto_20211016_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Answer',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
